### PR TITLE
Support for paths with spaces

### PR DESCRIPTION
**Pull request by episage**
I added `markedLinkRecognizer`. Syntax is markdown like:

```
[any text](/path to image with spaces here.png)
```

### CODE REVIEW

**Comment by kisstkondoros** [comment]
I'll look into this in depth in a couple of hours, looks great so far ;-)

**Comment by kisstkondoros** [comment]
During testing it I've found some minor issues, therefore I've removed the version bump, I'll merge it, and do the fixes on top of that.

Thanks for the PR!

**Comment by kisstkondoros** [comment]
Released with v0.26.1. Thanks for the contribution!

**Comment by episage** [comment]
Thx for the fixes

**Comment by episage** [comment]
Yes, I was struggling with making the relative path resolution work. Thanks again for the fixes

**Pull request merged**
